// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.startupExperimentPrefs.dom.push.alwaysConnect", true);
user_pref("app.normandy.startupRolloutPrefs.media.autoplay.default", 1);
user_pref("app.normandy.user_id", "7e6f3b67-f3b5-45ec-8cae-7a2ce58029d3");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1556189244);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1556189364);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1556199564);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1556189004);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1556188884);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1556189124);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1556189604);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1556189484);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 348160);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1556188734);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 78);
user_pref("browser.newtabpage.activity-stream.impressionId", "{7dfc1568-87d5-4aeb-84b8-3028b86b29da}");
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1556121600);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 3);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1556199962508");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1556201784508");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1556199068910");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1556202668910");
user_pref("browser.search.region", "CN");
user_pref("browser.slowStartup.averageTime", 2578);
user_pref("browser.slowStartup.samples", 1);
user_pref("browser.startup.homepage_override.buildID", "20190410113011");
user_pref("browser.startup.homepage_override.mstone", "66.0.3");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\"],\"currentVersion\":15,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.timesBeforeHidingSuggestionsHint", 0);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1556188743434");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "66.0.3");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.push.userAgentID", "cd15f416ba634947b3828b9292277677");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.databaseSchema", 28);
user_pref("extensions.getAddons.cache.lastUpdate", 1556189244);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppVersion", "66.0.3");
user_pref("extensions.lastPlatformVersion", "66.0.3");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"cbc02441-7b3a-459e-aee2-3bc02998d4e2\",\"screenshots@mozilla.org\":\"6ccffc87-171b-4ab0-8a17-a8d165053427\",\"webcompat-reporter@mozilla.org\":\"6a0e2968-6925-4756-acf0-32240b78ec28\",\"webcompat@mozilla.org\":\"dc12a126-3aa4-401e-9573-ecf252462c2b\"}");
user_pref("idle.lastDailyNotification", 1556189133);
user_pref("lightweightThemes.usedThemes", "[]");
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1556188977);
user_pref("media.gmp-gmpopenh264.version", "1.7.1");
user_pref("media.gmp-manager.buildID", "20190410113011");
user_pref("media.gmp-manager.lastCheck", 1556188975);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1556189133);
user_pref("places.history.expiration.transient_current_max_pages", 93838);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "79bddabf-5ed0-45c1-bea9-8f57d966bd03");
user_pref("security.sandbox.plugin.tempDirSuffix", "641d8ae4-978a-44b1-926f-5ef267b9813e");
user_pref("services.blocklist.addons.checked", 1556189301);
user_pref("services.blocklist.gfx.checked", 1556189301);
user_pref("services.blocklist.onecrl.checked", 1556189301);
user_pref("services.blocklist.pinning.checked", 1556189301);
user_pref("services.blocklist.plugins.checked", 1556189301);
user_pref("services.settings.clock_skew_seconds", -67);
user_pref("services.settings.last_etag", "\"1556133806451\"");
user_pref("services.settings.last_update_seconds", 1556197753);
user_pref("services.settings.main.language-dictionaries.last_check", 1556189301);
user_pref("services.settings.main.onboarding.last_check", 1556189301);
user_pref("services.settings.main.sites-classification.last_check", 1556189301);
user_pref("services.settings.main.tippytop.last_check", 1556189301);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1556189133);
user_pref("toolkit.startup.last_success", 1556188733);
user_pref("toolkit.telemetry.cachedClientID", "387dfccb-2ebf-404b-b2d0-3b6b475041f6");
user_pref("toolkit.telemetry.previousBuildID", "20190410113011");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
